name: aller_scan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  uuid: ^4.5.1
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
